[package]
name = "lapce"
version = "0.0.10"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"
rust-version = "1.58"
resolver = "2"

[dependencies]
lapce-proxy = { path = "./lapce-proxy" }
lapce-ui = { path = "./lapce-ui" }

[[bin]]
name = "lapce"
path = "lapce-ui/src/bin/lapce.rs"

[[bin]]
name = "lapce-proxy"
path = "lapce-proxy/src/bin/lapce-proxy.rs"

[workspace]
members = ["lapce-core", "lapce-data", "lapce-proxy", "lapce-rpc", "lapce-ui"]
